### ISSUE TITLE
Explicit bindings are required....

### ISSUE THREAD

**Issue by rsvancara** [kairosdb/kairos-carbon#12]
15:11:29.302 [main] INFO  [CarbonServerModule.java:31] - Configuring module CarbonServerModule
15:11:29.308 [main] INFO  [TelnetServerModule.java:42] - Configuring module TelnetServerModule
Exception in thread "main" com.google.inject.CreationException: Guice creation errors:

1) Explicit bindings are required and java.lang.String annotated with @com.google.inject.name.Named(value=kairosdb.carbon.pickle.address) is not explicitly bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=kairosdb.carbon.pickle.address)
    for parameter 2 at org.kairosdb.plugin.carbon.CarbonPickleServer.<init>(CarbonPickleServer.java:67)
  at org.kairosdb.plugin.carbon.CarbonServerModule.configure(CarbonServerModule.java:54)

2) Explicit bindings are required and java.lang.String annotated with @com.google.inject.name.Named(value=kairosdb.carbon.text.address) is not explicitly bound.
  while locating java.lang.String annotated with @com.google.inject.name.Named(value=kairosdb.carbon.text.address)
    for parameter 3 at org.kairosdb.plugin.carbon.CarbonTextServer.<init>(CarbonTextServer.java:63)
  at org.kairosdb.plugin.carbon.CarbonServerModule.configure(CarbonServerModule.java:53)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at org.kairosdb.core.Main.<init>(Main.java:198)
	at org.kairosdb.core.Main.main(Main.java:244)

**Comment by rsvancara** [comment]
You need to:

cp src/main/resources/kairos-carbon.properties ~/kairosdb/conf/

Glad I could help myself.....
