### ISSUE TITLE
kairos-carbon fails on first connction attempt from a carbon-relay

### ISSUE THREAD

**Issue by PsichoD** [kairosdb/kairos-carbon#14]
07-12|19:50:15.044 [main] INFO  [Main.java:306] - ------------------------------------------
07-12|19:50:15.045 [main] INFO  [Main.java:307] -      KairosDB service started
07-12|19:50:15.045 [main] INFO  [Main.java:308] - ------------------------------------------
07-12|19:50:15.123 [New I/O server boss #34] WARN  [JdkLogger.java:80] - Failed to accept a connection.
java.lang.NoClassDefFoundError: net/razorvine/pickle/Unpickler
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_101]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803) ~[na:1.7.0_101]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_101]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_101]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_101]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_101]
	at org.kairosdb.plugin.carbon.PickleDecoder.<init>(PickleDecoder.java:19) ~[kairos-carbon-1.0.jar:1.0.20160712163842]
	at org.kairosdb.plugin.carbon.CarbonPickleServer.getPipeline(CarbonPickleServer.java:88) ~[kairos-carbon-1.0.jar:1.0.20160712163842]
	at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134) ~[netty-3.6.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104) ~[netty-3.6.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[netty-3.6.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42) ~[netty-3.6.5.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_101]
Caused by: java.lang.ClassNotFoundException: net.razorvine.pickle.Unpickler
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_101]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_101]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_101]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_101]
	... 21 common frames omitted
07-12|19:50:16.125 [New I/O server boss #34] WARN  [JdkLogger.java:80] - Failed to accept a connection.
java.lang.NoClassDefFoundError: org/kairosdb/plugin/carbon/pickle/Unpickler
	at org.kairosdb.plugin.carbon.PickleDecoder.<init>(PickleDecoder.java:19) ~[kairos-carbon-1.0.jar:1.0.20160712163842]
	at org.kairosdb.plugin.carbon.CarbonPickleServer.getPipeline(CarbonPickleServer.java:88) ~[kairos-carbon-1.0.jar:1.0.20160712163842]
	at org.jboss.netty.channel.socket.nio.NioServerBoss.registerAcceptedChannel(NioServerBoss.java:134) ~[netty-3.6.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:104) ~[netty-3.6.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[netty-3.6.5.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42) ~[netty-3.6.5.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_101]
07-12|19:50:23.715 [Hector.me.prettyprint.cassandra.connection.CassandraHostRetryService-1] DEBUG [CassandraHostRetryService.java:123] - Retry service fired... nothing to do.
07-12|19:50:33.716 [Hector.me.prettyprint.cassandra.connection.CassandraHostRetryService-1] DEBUG [CassandraHostRetryService.java:123] - Retry service fired... nothing to do.
07-12|19:50:43.014 [QuartzScheduler_QuartzSchedulerThread] DEBUG [QuartzSchedulerThread.java:268] - batch acquisition of 1 triggers
07-12|19:50:43.716 [Hector.me.prettyprint.cassandra.connection.CassandraHostRetryService-1] DEBUG [CassandraHostRetryService.java:123] - Retry service fired... nothing to do.

**Comment by brianhks** [comment]
Your missing the pyrolite.jar file that is in the project.  It needs to be deployed as well.

**Comment by KayBeSee** [comment]
> Your missing the pyrolite.jar file that is in the project. It needs to be deployed as well.

Hey, I know this issue is dead but I was wondering if you could help me out and elaborate on how to deploy the .jar file as well? I wrote a plugin for kairos that uses a class from a jar file but I can't figure out how to get it to build with it. 

I am getting an error message similar to the one posted above.

```
java.lang.NoClassDefFoundError: com/clearspring/analytics/stream/quantile/TDigest
	at org.kairosdb.plugin.losant.MedianAggregator$MedianDataPointAggregator.getNextDataPoints(MedianAggregator.java:62)
```

I added these lines to my kairosdb-plugin.properties file like in [this doc](https://kairosdb.github.io/docs/build/html/kairosdevelopment/Plugins.html#plugins-with-extra-dependencies) but still get the error

```
kairosdb.service.TDigest=com.clearspring.analytics.stream.quantile.TDigest;
kairosdb.service_folder.TDigest=tools
```
