### ISSUE TITLE
Pickle port not working

### ISSUE THREAD

**Issue by vamsikorada** [kairosdb/kairos-carbon#15]
I am trying to push metrics to carbon pickle port and am getting the following error.

```
11:50:44.471 [New I/O worker #18] ERROR [CarbonPickleServer.java:166] - Error processing pickle
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to org.kairosdb.plugin.carbon.pickle.PickleMetric
    at org.kairosdb.plugin.carbon.CarbonPickleServer.messageReceived(CarbonPickleServer.java:104) ~[kairos-carbon-1.0.jar:1.0.20160614120906]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:107) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:88) ~[netty-3.6.5.Final.jar:na]
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.6.5.Final.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

```

We are going to production in a week and need this to be fixed for that. Can someone please help me resolve the issue.

**Comment by brianhks** [comment]
I just posted a new build that is updated to kairos 1.1.1.  Please verify if it works and make sure you have included the pyrolite.jar file that is checked into the project.

**Comment by vamsikorada** [comment]
Hi brianhks, I tried with new version and still getting the same error.
The Unpickler is checking for TUPLE2, where as the data I am getting is starting with TUPLE and does not contain TUPLE2.
I am using dropwizard library to send the pickled data.

**Comment by jonhadfield** [comment]
Same issue for me, using:
https://github.com/kairosdb/kairosdb/releases/download/v1.1.1/kairosdb-1.1.1-1.tar.gz
https://github.com/kairosdb/kairos-carbon/releases/download/v1.1-1/kairos-carbon-1.1.tar.gz

```
18:29:18.577 [New I/O worker #7] ERROR [CarbonPickleServer.java:166] - Error processing pickle
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to org.kairosdb.plugin.carbon.pickle.PickleMetric
at org.kairosdb.plugin.carbon.CarbonPickleServer.messageReceived(CarbonPickleServer.java:104) ~[kairos-carbon-1.1.jar:1.1.20160801202051]
...
```

**Comment by vamsikorada** [comment]
Hi @jonhafield, we faced the same issue and made some changes in the unpickler to fix the issue. You can go through it here https://github.com/walmart/kairos-carbon/pull/1/files
However, it is yet to be properly tested by us, though it passed all our preliminary testing. :)

**Comment by jonhadfield** [comment]
Hi @vamsikorada, I just built from your branch: https://github.com/walmart/kairos-carbon/tree/vamsikorada-devbranch1 and I'm now also able to push using pickle.
Thanks!

**Comment by vamsikorada** [comment]
@brianhks  Raised a pull request, which addresses this issue. Please look into it. (https://github.com/kairosdb/kairos-carbon/pull/17)
